Added integration tests for vmc_dhcp_profiles execution module. Update of PR-86
saltstack/salt-ext-modules-vmware pull request #142
Opened 2021-11-16 09:34 UTC by shaikres

Added integration tests for vmc_dhcp_profiles execution module. Update of [https://github.com/saltstack/salt-ext-modules-vmware/pull/86](url)

2021-11-16 16:32 UTC, waynew requested changes
**suggestion** while the way this is written *does* pass tests running locally, the way it's written is not very clear at all, and is very difficult to follow. 
We could review it during one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule), but generally there's a lot of boilerplate/duplication setup code.

There may be a better way, but my first impression is that these tests should basically look like this:

```
def test_create_dhcp_profile(salt_call_cli, vmc_dhcp_create_kwargs, dhcp_profile_id):
    ret = salt_call_cli.run("vmc_dhcp_profiles.create", **vmc_dhcp_create_kwargs)
    result_as_json = ret.json
    assert result_as_json["id"] == result_as_json["display_name"] == dhcp_profile_id
```

That might not be the best approach (maybe `server_addresses` should also be provided within the test, for instance?), but generally peeling the common args/functionality into a fixture or fixtures tends to make tests easier to follow.

2021-11-17 00:17 UTC, waynew commented
@shaikres On today's Test Clinic I went through and refactored this set of integration tests into something that's more like what we want to see: [Like this](https://github.com/jain-prerna/salt-ext-modules-vmware-1/compare/vmc_dhcp_integration_tests...waynew:vmc_dhcp_integration_tests).

Let me know if you have any questions -- but that's the kind of setup that we're looking for :+1:

2021-11-17 14:17 UTC, shaikres commented
> @shaikres On today's Test Clinic I went through and refactored this set of integration tests into something that's more like what we want to see: [Like this](https://github.com/jain-prerna/salt-ext-modules-vmware-1/compare/vmc_dhcp_integration_tests...waynew:vmc_dhcp_integration_tests).
> 
> Let me know if you have any questions -- but that's the kind of setup that we're looking for 👍

Thanks Wayne, we have gone through the code and applied refactoring to our tests.

2021-11-17 15:52 UTC, waynew approved these changes

2021-11-17 16:34 UTC, merged