set ntp config module
saltstack/salt-ext-modules-vmware pull request #323
Opened 2022-11-17 00:00 UTC by joechainz

2022-11-17 01:56 UTC, waynew requested changes
Looks excellent! The only thing that I think we could do here is write a quick unit tests:

```
def test_whatever(fake_service_instance):
    esxi.set_ntp_config(service_instance=fake_service_instance)  # and whatever else
```

May or may not be worth adding some other bits :shrug:. That's just to make sure the service instance bit works as expected :shrug:

2022-11-17 16:59 UTC, joechainz commented on src/saltext/vmware/modules/esxi.py
> +            ntp_config = vim.host.NtpConfig()
pyvmomi library

2022-11-17 17:24 UTC, waynew commented on src/saltext/vmware/modules/esxi.py
> +def set_ntp_config(
Were those just for connecting? Our `get_service_instance` will read those values from the config.

2022-11-17 20:10 UTC, joechainz commented on src/saltext/vmware/modules/esxi.py
> +            ntp_config = vim.host.NtpConfig()
This comes from the pyvmomi lib.

2022-11-17 22:27 UTC, dmurphy18 approved these changes

2022-11-18 01:39 UTC, waynew approved these changes
looks good, I'm down to merge tomorrow unless there are objections 👍

2022-11-18 14:31 UTC, waynew requested changes
Oh yeah - @dmurphy18 made a great point, we need a changelog file here

2022-11-18 21:59 UTC, waynew requested changes

2022-11-18 21:59 UTC, waynew commented on CHANGELOG.md
> +# [22.11.18]
**suggestion** this should be in the changelog/NNN.added - if there was no issue created here in the repo can just be 323.added (and it should say "Added vmware_esxi.set_ntp_config module" probably)

2022-11-18 23:06 UTC, waynew approved these changes
:+1: LGTM

2022-11-18 23:07 UTC, waynew commented
Pre-commit just failing on the changelog file, we should probably see if we can make that... not happen :joy:

2022-11-18 23:07 UTC, merged