Update README.md to include instructions for required missing steps
saltstack/salt-ext-modules-vmware pull request #340
Opened 2023-01-11 20:30 UTC by dmurphy18

Updated the README.md to add additional steps that I found were missing from the instructions in order to successfully access the vCenter

2023-01-11 22:45 UTC, joechainz approved these changes
Looks good to me!

2023-01-12 18:06 UTC, merged

2023-01-12 18:06 UTC, waynew requested changes
Couple of changes - spotted a typo, and also prepping for changes that are on the horizon.

2023-01-12 18:06 UTC, waynew commented on README.md
> +      user: insert_user_name
**suggestion** Use TEST-NET IP or example.com domain. Also update to use our modern key.

```suggestion
    saltext.vmware:
        # Or use IP address, e.g. 203.0.113.42
        host: vsphere.example.com
        password: CorrectHorseBatteryStaple
        user: BobbyTables
```

2023-01-12 18:06 UTC, waynew commented on README.md
> +    # 8. Create a test config file:
**suggestion** let's rewrite this:

```suggestion
    # 8. (deprecated but not removed yet) If you're contributing to the project and need to run the tests, create a test config file:
```

2023-01-12 18:06 UTC, waynew commented on README.md
> +    # 8. Create a test config file for VMC:
**suggestion** same as test config file - deprecated but not removed yet.