add config module dependency.
saltstack/salt-ext-modules-vmware pull request #386
Opened 2023-10-17 22:48 UTC by murugesan-raja

2023-10-17 23:29 UTC, dmurphy18 requested changes
Need to not use personal spaces and run pre-commit

2023-10-17 23:29 UTC, dmurphy18 commented on setup.cfg
> +    config-modules@https://github.com/saltstack/salt-ext-modules-vmware/raw/ramurugesan-unified-config-poc/src/saltext/vmware/archive/config_modules-0.0.4-py3-none-any.whl
@murugesan-raja Adding personal locations into what is supposed to be this branch is not recommended best practice.
Also the failure to run any pre-commit on this PR implies, not taking regular steps for salt repositories.
Can contact me and we can go through this over zoom if that would help

2023-10-18 19:02 UTC, murugesan-raja commented on setup.cfg
> +    config-modules@https://github.com/saltstack/salt-ext-modules-vmware/raw/ramurugesan-unified-config-poc/src/saltext/vmware/archive/config_modules-0.0.4-py3-none-any.whl
@dmurphy18 Thank you for helping with pre-commit. It is now green.

2023-10-18 19:04 UTC, murugesan-raja commented on setup.cfg
> +    config-modules@https://github.com/saltstack/salt-ext-modules-vmware/raw/ramurugesan-unified-config-poc/src/saltext/vmware/archive/config_modules-0.0.4-py3-none-any.whl
About URL specifiers. This approach is mentioned in https://pip.pypa.io/en/stable/reference/requirement-specifiers 
Example:
pip @ https://github.com/pypa/pip/archive/22.0.2.zip
requests [security] @ https://github.com/psf/requests/archive/refs/heads/main.zip ; python_version >= "3.11"

2023-10-25 01:22 UTC, closed without merging