Adding state and execution modules for compliance workflows.
saltstack/salt-ext-modules-vmware pull request #404
Opened 2024-07-16 21:39 UTC by balavigneshVMware

Changes include:
1. a state module to invoke dry-run (check compliance) and remediate workflows for compliance controls, for components in VCF.
2. an execution module to invoke the corresponding compliance workflows thru the config-modules interface.
3. utils class to create product contexts.
4. unit tests.

[changes will be merged only after config-module dependency (https://github.com/vmware/vmware-config-modules) is available thru pypi].

2024-07-16 22:42 UTC, ravi-pratap-s commented on src/saltext/vmware/states/compliance_control.py
> +    # Create ESXi configuration
nit: Can we remove this line?

2024-07-17 16:46 UTC, dmurphy18 requested changes
Should have passing tests before asking for reviews etc.
And needs a changelog associated with the PR

2024-07-17 17:42 UTC, balavigneshVMware commented
> Should have passing tests before asking for reviews etc. And needs a changelog associated with the PR

Waiting on pypi publish on config-modules, hence marked this PR as "Draft" and haven't marked it "Ready for review" yet. I was not aware github sends notifications even if not "Ready for review".

2024-07-17 17:50 UTC, dmurphy18 commented
@balavigneshVMware Got a github email requesting review, so thought you guys had sent it as 'Ready for review'.
Wondering why testing is waiting on config-modules to be published, since you can always Mock objects and functions to test the code changes etc. Would have thought that to be standard practice, so not reliant on exterior modules, etc.

2024-08-05 20:24 UTC, balavigneshVMware commented
@dmurphy18, the linux based tests have passed, however docs pipeline is failing with SSL errors reaching out to developer.vmware.com. Do you know who can help with this?

2024-08-05 20:32 UTC, dmurphy18 commented
@balavigneshVMware Sorry, our doc writer recently quit, and the SRE that could take a look is away at a conference till the end of the week.. Wondering if you are getting hit by things moving around in the infrastructure, what with the push from AWS to GCP (Google Compute Platform ?).

With failure in SSL Certs, that is rights and infrastructure underneath, perhaps your own SRE can take a look at this, otherwise could ask our SRE when he returns, next week.

2024-08-05 22:02 UTC, dmurphy18 commented
@ScriptAutomate Can you take a look at this when back from the conference, looks like some certs need updating.

2024-08-13 18:43 UTC, ScriptAutomate commented
> Looks like the docs were migrated to broadcom web portal and the SSL certs might need updating (maybe?). Let me wait for your SRE as we don't have much info on the pipelines.

@balavigneshVMware The issue is that all of those links are invalid. If you attempt to go to them, they all merely go to the landing page of the Broadcom developer portal (different domain names, thus the SSL certificate check gets confused).

This leaves you with two options:

1. Fix all the links. The `linkcheck` tools in Sphinx is to help ensure that links throughout the documentation are accurate. Right now, all of the links flagged in the output are invalid. This means you are directing users/devs to pages that don't actually help.
2. You can choose to keep all of these invalid links (not recommended), and can update the `docs/conf.py` autodoc config where the `linkcheck_ignore` is defined and expand the URLs it should ignore:

```python
# <---- Autodoc Config -----------------------------------------------------------------------------------------------

linkcheck_timeout = 10
if not os.environ.get("SKIP_LINKCHECK_IGNORE"):
    linkcheck_ignore = [
        "https://docs.github.com/en/authentication/connecting-to-github-with-ssh",
        "http://pubs.vmware.com",
        "https://developer.vmware.com",
        "https://code.vmware.com"
    ]
```

2024-08-19 20:11 UTC, dmurphy18 commented
@balavigneshVMware FYI - pytest-skip-markers was recently updated (1.5.2) to correctly support MacOS Arm64, don't think you guys support MacOS but just in case.

2024-09-03 16:44 UTC, dmurphy18 approved these changes
didn't see anything obvious

2024-09-03 19:17 UTC, merged